//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pulsar_Pack_Creator {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PulsarRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PulsarRes() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pulsar_Pack_Creator.PulsarRes", typeof(PulsarRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   #BMG
        ///
        ///   3f7  = Wiimmfi (1人)
        ///   58a  = {CC}cc
        ///   7dd	= Wiimmfi
        ///   7de	= Riivolutionチャンネル
        ///   7e8	= インターネットにつないであそびます
        ///   7e9	= ２人で　インターネットにつないであそびます
        ///   7ea	= Riivolutionに　移動します
        ///   7f1	= Wiimmfi (1人)
        ///   7f2	= Wiimmfi (2人)
        ///   818	= インターネットから切断して\nメインメニューにもどります。
        ///   841	= \z{602,0}さん\n\z{802,120000}\nさん\n２人でインターネットに接続します。
        ///   bbf  = {CC}cc\n\z{800,32}バイクのみ
        ///   bc3  = {CC}cc\n\z{800,32}カート＆バイク
        ///   d54  = {CC}cc
        ///   d58  = {CC}cc class for experts.
        ///   fa8	= There are no Friends registered\nin your Frie [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BMG {
            get {
                return ResourceManager.GetString("BMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] Channel {
            get {
                object obj = ResourceManager.GetObject("Channel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] Code {
            get {
                object obj = ResourceManager.GetObject("Code", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] CommonAssets {
            get {
                object obj = ResourceManager.GetObject("CommonAssets", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] cygcrypto_1_1 {
            get {
                object obj = ResourceManager.GetObject("cygcrypto_1_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] cygncursesw_10 {
            get {
                object obj = ResourceManager.GetObject("cygncursesw_10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] cygpng16_16 {
            get {
                object obj = ResourceManager.GetObject("cygpng16_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] cygwin1 {
            get {
                object obj = ResourceManager.GetObject("cygwin1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] cygz {
            get {
                object obj = ResourceManager.GetObject("cygz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] Earth {
            get {
                object obj = ResourceManager.GetObject("Earth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] Globe {
            get {
                object obj = ResourceManager.GetObject("Globe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] Loader {
            get {
                object obj = ResourceManager.GetObject("Loader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   800018a8 0x800018a8
        ///80001d50 0x80001d50
        ///80001d6c 0x80001d6c
        ///80001d90 0x80001d90
        ///80001dc0 0x80001dc0
        ///80001de8 0x80001de8
        ///80001dec 0x80001dec
        ///80001e14 0x80001e14
        ///80001e30 0x80001e30
        ///80001f1c 0x80001f1c
        ///80001f40 0x80001f40
        ///80001f54 0x80001f54
        ///80002440 0x80002440
        ///8000245c 0x8000245c
        ///8000249c __TRKreset
        ///80005f34 memcpy
        ///80005f84 __fill_mem
        ///80006038 memset
        ///80006068 __check_pad3
        ///80006090 __set_debug_bba
        ///8000609c __get_debug_bba
        ///800060a4 __start
        ///80006210 __init_registers
        ///800062a0 __init_data
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MAP {
            get {
                return ResourceManager.GetString("MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] MenuMulti {
            get {
                object obj = ResourceManager.GetObject("MenuMulti", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] MenuOther {
            get {
                object obj = ResourceManager.GetObject("MenuOther", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] MenuSingle {
            get {
                object obj = ResourceManager.GetObject("MenuSingle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] RaceAssets {
            get {
                object obj = ResourceManager.GetObject("RaceAssets", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] Title {
            get {
                object obj = ResourceManager.GetObject("Title", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] Title_J {
            get {
                object obj = ResourceManager.GetObject("Title_J", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] UIAssets {
            get {
                object obj = ResourceManager.GetObject("UIAssets", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   [P]
        ///#Base version: MKWii PAL
        ///80000000-*: +0x0
        ///#
        ///[E]
        ///80000000-8000802f: +0x0
        ///8000808c-8000adbb: -0x40
        ///8000af24-8000b6b3: -0xa0
        ///8000b6b4-8000c173: +0x15994
        ///8000c174-80021ba7: -0xb60
        ///80021ba8-80225f1b: -0xa0
        ///802261f8-802402df: -0x384
        ///802402e0-80240e17: +0x3f1c
        ///80240e18-80244dd3: -0xebc
        ///80276054-8027b000: -0x4340
        ///802a3d60-802a407f: -0x4368
        ///802a4080-80386e3f: -0x4380
        ///80386f48-80386f8f: -0x4388
        ///805103b4-80510a8f: -0x4380
        ///80510b84-8052d297: -0x4474
        ///8052d298-8052d96b: +0x22568
        ///8052d96c-8053d97b [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string versions {
            get {
                return ResourceManager.GetString("versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] wbmgt {
            get {
                object obj = ResourceManager.GetObject("wbmgt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] wimgt {
            get {
                object obj = ResourceManager.GetObject("wimgt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] wszst {
            get {
                object obj = ResourceManager.GetObject("wszst", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   &lt;wiidisc version=&quot;1&quot;&gt;
        ///	&lt;id game=&quot;RMC&quot;/&gt;
        ///	&lt;options&gt;
        ///		&lt;section name=&quot;{$pack}&quot;&gt;
        ///			&lt;option name=&quot;Pack&quot;&gt;
        ///				&lt;choice name=&quot;Enabled&quot;&gt;
        ///					&lt;patch id=&quot;{$pack}LoadPack&quot;/&gt;
        ///				&lt;/choice&gt;
        ///			&lt;/option&gt;
        ///			&lt;option name=&quot;My Stuff&quot;&gt;
        ///				&lt;choice name=&quot;From CTGP-r&quot;&gt;
        ///					&lt;patch id=&quot;CTGPLoad&quot;/&gt;
        ///				&lt;/choice&gt;
        ///				&lt;choice name=&quot;From Pack&quot;&gt;
        ///					&lt;patch id=&quot;{$pack}Load&quot;/&gt;
        ///				&lt;/choice&gt;
        ///			&lt;/option&gt;
        ///		&lt;/section&gt;
        ///	&lt;/options&gt;	
        ///	&lt;patch id=&quot;{$pack}LoadPack&quot;&gt;
        ///		&lt;memory offset=&quot;0x80242698&quot; value=&quot;4BDC1968&quot; origina [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XML {
            get {
                return ResourceManager.GetString("XML", resourceCulture);
            }
        }
    }
}
